version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver" # THIS IS CRUCIAL
      - "--web.enable-lifecycle" # Allows config reloads
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Admin@123
    extra_hosts:
      - "host.docker.internal:host-gateway" # Add this
    networks:
      - monitoring-net
    depends_on:
      - prometheus

networks:
  monitoring-net:
    name: monitoring-net
    attachable: true # Add this

volumes:
  grafana-storage:
    driver: local
