global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Remote write configuration (receiver)
remote_write:
  - url: http://localhost:9090/api/v1/write

# Remote read configuration (optional)
# remote_read:
#   - url: http://localhost:9090/api/v1/read

scrape_configs:
  - job_name: "k6"
    static_configs:
      - targets: ["localhost:9090"]
